config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  namespace :admin do
    resources :installers

  end
  resources :comments
  devise_for :users
  resources :projects do
    get '/comments/:id', to: 'comments#destroy'
    resources :comments
  member do
    delete "delete_upload/:upload_id", action: :delete_upload
  end
end

  root 'home#index'


end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  enum projtype: ['Access Control', 'Video Surveillance', 'Access Control & Video Surveillance']
  has_one :proj_status, :foreign_key => "status_id", :primary_key => 'status_id'
  has_many_attached :uploads
  has_many :comments, dependent: :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  add_breadcrumb "Home", :root_path
  add_breadcrumb "Projects", :projects_path
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.joins(:proj_status).order("created_at DESC")
    @title = 'Projects - Summary'

  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @projects = Project.joins(:proj_status).order("created_at DESC")
    @comments = Comment.where(project_id: @project).order("created_at DESC")
    @comment = Comment.new
      add_breadcrumb "Project Details", :projects_path

  end

  def delete_upload
    @attachment = ActiveStorage::Attachment.find(params[:upload_id])
    @attachment.purge # or use purge_later
    redirect_back(fallback_location: projects_path)
  end

  # GET /projects/new
  def new
    @project = Project.new
    @projstatus = ProjStatus.all
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)
    respond_to do |format|
      if @project.save

        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
        params.require(:project).permit(:projname, :startdate, :enddate,
          :installer, :createdby, :cpdcprojnum, :projmanager, :customername, :customerphone,
          :customeremail, :projtype, :building, :rooms, :description, :status_id, uploads: [])
    end
end

app/views/projects/_form.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'bootstrap-datepicker/bootstrap-datepicker.css', media: 'all' %>
  <%= stylesheet_link_tag 'bootstrap-daterangepicker/bootstrap-daterangepicker.css', media: 'all' %>
  <%= stylesheet_link_tag 'bootstrap-material-datetimepicker/bootstrap-material-datetimepicker.css', media: 'all' %>
  <%= stylesheet_link_tag 'timepicker/timepicker.css', media: 'all' %>
  <%= stylesheet_link_tag 'minicolors/minicolors.css', media: 'all' %>
<% end %>

<% content_for :scripts do %>
  <!-- Dependencies -->
  <%= javascript_include_tag 'moment/moment.js' %>
  <%= javascript_include_tag 'bootstrap-datepicker/bootstrap-datepicker.js' %>
  <%= javascript_include_tag 'bootstrap-daterangepicker/bootstrap-daterangepicker.js' %>
  <%= javascript_include_tag 'bootstrap-material-datetimepicker/bootstrap-material-datetimepicker.js' %>
  <%= javascript_include_tag 'timepicker/timepicker.js' %>
  <%= javascript_include_tag 'minicolors/minicolors.js' %>
  <%= javascript_include_tag 'forms_pickers.js' %>
<% end %>




<div class="card mb-4">
  <h6 class="card-header">
    Create New Project
  </h6>
  <div class="card-body">
    <%= form_with(model: project, local: true, :validate => true) do |f| %>
    <% if project.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

        <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
      <div class="form-group row">
        <%= f.label :projname, 'Project Name', { :class=>"col-form-label col-sm-2 text-sm-right" } %>

        <div class="col-sm-10">
          <%= f.text_field :projname, { :class=>"form-control", autofocus: true, required: true } %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :status_id, 'Status', { :class=>"col-form-label col-sm-2 text-sm-right" } %>

        <div class="col-sm-10">
          <%= f.select :status_id,
                                   options_from_collection_for_select(ProjStatus.all, 'status_id', 'statusdescr'), {},  :class=>'form-control m-b'  %>

        </div>

      </div>

      <div class="form-group row">
        <%= f.label :startdate, 'Start Date', { :class=>"col-form-label col-sm-2 text-sm-right" } %>

        <div class="col-sm-10">

          <%= f.text_field :startdate,
          :value => Time.now.strftime('%m/%d/%Y'),
          :class=>"form-control", id: 'datepicker-base'  %>


        </div>
      </div>

      <div class="form-group row">
        <%= f.label :enddate, 'End Date', { :class=>"col-form-label col-sm-2 text-sm-right" } %>

        <div class="col-sm-10">

          <%= f.text_field :enddate,
          :value => Time.now.strftime('%m/%d/%Y'),
          :class=>"form-control", id: 'datepicker-base2' %>


        </div>
      </div>

      <div class="form-group row">
        <%= f.label :installer, 'Installer', { :class=>"col-form-label col-sm-2 text-sm-right" } %>

        <div class="col-sm-10">
          <%= f.text_field :installer, { :class=>"form-control" } %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :cpdcprojnum, 'CPDC Project Number', { :class=>"col-form-label col-sm-2 text-sm-right" } %>

        <div class="col-sm-10">
          <%= f.text_field :cpdcprojnum, { :class=>"form-control" } %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :projmanager, 'ProjectManager', { :class=>"col-form-label col-sm-2 text-sm-right" } %>

        <div class="col-sm-10">
          <%= f.text_field :projmanager, { :class=>"form-control" } %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :customername, 'Customer Name', { :class=>"col-form-label col-sm-2 text-sm-right" } %>

        <div class="col-sm-10">
          <%= f.text_field :customername, { :class=>"form-control" } %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :customerphone, 'Customer Phone', { :class=>"col-form-label col-sm-2 text-sm-right" } %>

        <div class="col-sm-10">
          <%= f.text_field :customerphone, { :class=>"form-control" } %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :customeremail, 'Customer Email', { :class=>"col-form-label col-sm-2 text-sm-right" } %>

        <div class="col-sm-10">
          <%= f.text_field :customeremail, { :class=>"form-control" } %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :projtype, 'Project Type', { :class=>"col-form-label col-sm-2 text-sm-right" } %>

        <div class="col-sm-10">
          <%= f.select :projtype, Project.projtypes.keys, {include_blank: true}, class: 'custom-select' %>
        </div>

      </div>
      <div class="form-group row">
        <%= f.label :building, 'Building', { :class=>"col-form-label col-sm-2 text-sm-right" } %>

        <div class="col-sm-10">
        <%= f.text_field :building, { :class=>"form-control" } %>
        </div>

      </div>

      <div class="form-group row">
        <%= f.label :rooms, 'Rooms', { :class=>"col-form-label col-sm-2 text-sm-right" } %>

        <div class="col-sm-10">
        <%= f.text_field :rooms, { :class=>"form-control" } %>
        </div>

      </div>

      <div class="form-group row">
        <%= f.label :description, 'Project Description', { :class=>"col-form-label col-sm-2 text-sm-right" } %>

        <div class="col-sm-10">
        <%= f.text_area :description, { :class=>"form-control" } %>
        </div>

      </div>

      <div class="form-group row">
        <%= f.label :uploads, 'File Uploads', { :class=>"col-form-label col-sm-2 text-sm-right" } %>

        <div class="col-sm-10">
        <%= f.file_field :uploads, multiple: true, class: "form-control" %>
        </div>

      </div>

      <div class="form-group row">
        <div class="col-form-label col-sm-2 text-sm-right">
        </div>


        <div class="col-sm-10">

          <%= button_tag type: 'submit', class: "btn btn-success" do %>
            <span class="ion ion-md-add"></span> &nbsp;&nbsp;<% if ( f.object.new_record? ) %>Create Project<% else %>Update Project<% end %>

          <% end %>
          <%= link_to 'Cancel', projects_path, { :class=>"btn btn-secondary" } %>
        </div>

      </div>


    <% end %>
  </div>
</div>

app/views/projects/edit.html.erb
<h4 class="font-weight-bold py-3 mb-4">
  <span class="text-muted font-weight-light">Projects /</span> Edit Project
</h4>

<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'bootstrap-daterangepicker/bootstrap-daterangepicker.css', media: 'all' %>
  <%= stylesheet_link_tag 'datatables/datatables.css', media: 'all' %>
<% end %>

<% content_for :scripts do %>
  <!-- Dependencies -->
  <%= javascript_include_tag 'moment/moment.js' %>
  <%= javascript_include_tag 'bootstrap-daterangepicker/bootstrap-daterangepicker.js' %>
  <%= javascript_include_tag 'datatables/datatables.js' %>
  <%= javascript_include_tag 'tables_datatables.js' %>
  <%= javascript_include_tag 'pages_tickets_list.js' %>
<% end %>

<h4 class="d-flex justify-content-between align-items-center w-100 font-weight-bold py-3 mb-4">
  <div class="card-body demo-vertical-spacing">
    <ol class="breadcrumb">
      <li class="breadcrumbs"><%= render_breadcrumbs %> </li>

    </ol>
  </div>


  <%= link_to new_project_path, method: :get do %>
  <button type="button" class="btn btn-primary btn-round d-block"><span class="ion ion-md-add"></span>&nbsp; Create project</button>
  <% end %>
</h4>

<!-- Filters -->
<%= form_with(model: @project, local: true, :validate => true) do |f| %>
<div class="ui-bordered px-4 pt-4 mb-4">
  <div class="form-row">
    <div class="col-md mb-4">
      <label class="form-label">Type</label>
      <%= f.select :projtype, Project.projtypes.keys, {:include_blank=> 'All Project Types'}, class: 'custom-select' %>
    </div>
    <div class="col-md mb-4">
      <label class="form-label">Status</label>
      <%= f.select :status_id,options_from_collection_for_select(ProjStatus.all, 'status_id', 'statusdescr'), {:include_blank=> true},  :class=>'custom-select'  %>

    </div>
    <div class="col-md mb-4">
      <label class="form-label">Created date</label>
      <input type="text" id="tickets-list-created" class="form-control">
    </div>
    <div class="col-md col-xl-2 mb-4">
      <label class="form-label d-none d-md-block">&nbsp;</label>
      <button type="button" class="btn btn-secondary btn-block">Show</button>
    </div>
  </div>
</div>
<% end %>
<!-- / Filters -->

<div class="card">
  <div class="card-datatable table-responsive">
    <table class="datatables-demo table table-striped table-bordered" data-turbolinks='false'>
      <thead>
        <tr>
          <th>Status</th>
          <th>Project Name</th>
          <th>Project Manager</th>
          <th>Created On</th>
          <th>Last update</th>
          <th>Completion</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @projects.each do |project| %>
        <tr>
          <td><span class="btn btn-<%= project.proj_status.statusnotify %> btn-xs md-btn-flat "><%= project.proj_status.statusdescr %></span></td>
          <td><%= project.projname %></td>
          <td><%= project.projmanager %></td>
          <td><%= project.created_at.to_time.strftime('%B %e at %l:%M %p') %></td>
          <td><%= project.updated_at.to_time.strftime('%B %e at %l:%M %p') %></td>
          <td><div class="progress" style="height: 4px;">
            <div class="progress-bar" style="width: <%= project.proj_status.percent %>%"></div>
          </div></td>
          <td>



          <%= link_to project_path(project), class: 'btn btn-outline-secondary btn-sm' do %>
            <span class="ion ion-md-albums"></span> View
          <% end %>
          <% if current_user.try(:admin?) %>


            <%= link_to edit_project_path(project) , { :class=>"btn btn-outline-secondary btn-sm" } do %>
            <span class="ion ion-md-create"></span> Edit
              <% end %>
              <% end %>
              </td>

        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/projects/new.html.erb
<div class="cui-example cui-example-vertical-spacing">
  <ol class="breadcrumb">
    <h4 class="font-weight-bold">
    <li class="breadcrumb-item">
    <%= render_breadcrumbs :separator => " / " %>
    </li>
    </h4>
  </ol>

<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'bootstrap-daterangepicker/bootstrap-daterangepicker.css', media: 'all' %>
  <%= stylesheet_link_tag 'datatables/datatables.css', media: 'all' %>
<% end %>

<% content_for :scripts do %>
  <!-- Dependencies -->
  <%= javascript_include_tag 'moment/moment.js' %>
  <%= javascript_include_tag 'bootstrap-daterangepicker/bootstrap-daterangepicker.js' %>
  <%= javascript_include_tag 'datatables/datatables.js' %>



<% end %>

<h4 class="py-3 mb-4">
  <ol class="breadcrumb font-weight-bold m-0">
    <li class="breadcrumb-item">  <%= link_to 'Projects', projects_path %></li>
    <li class="breadcrumb-item active"><%= @project.cpdcprojnum %> - <%= @project.projname %> </small></li>
  </ol>
</h4>

<!-- Header -->
<div class="border-right-0 border-left-0 ui-bordered container-m--x mb-4">
  <div class="row no-gutters row-bordered row-border-light">
    <div class="col-md-9">
      <div class="media-body container-p-x py-4">
        <div class="d-flex justify-content-between align-items-center mb-1">
          <div><strong class="text-primary text-large"><%= @project.proj_status.percent %>%</strong> completed</div>

            <% if current_user.try(:admin?) %>
            <div>
              <%= link_to edit_project_path(@project) , { :class=>"btn btn-outline-secondary btn-sm" } do %>
              <span class="ion ion-md-create"></span> Edit Project

                <% end %>
                <%= link_to 'Projects List', projects_path , { :class=>"btn btn-outline-secondary btn-sm" } %>

                </div>
                <% else %>
                <div>
                  <%= link_to 'Projects List', projects_path , { :class=>"btn btn-outline-secondary btn-sm" } %>
                </div>

                <% end %>


        </div>

        <div class="progress" style="height: 4px;">
          <div class="progress-bar" style="width: <%= @project.proj_status.percent %>%;"></div>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="container-p-x py-4">
        <div class="text-muted small">Status</div>
        <strong class="text-success text-big"><%= @project.proj_status.statusdescr %></strong>
      </div>
    </div>
  </div>
</div>
<!-- / Header -->

<div class="row">
  <div class="col">

    <!-- Description -->
    <div class="card mb-4">
      <h6 class="card-header">Description</h6>
      <div class="card-body">
      <p><%= @project.description %>
      </P>

      </div>
    </div>
    <!-- / Description -->

    <!-- Attached files -->
    <div class="card mb-4">
      <h6 class="card-header">Attached files</h6>
      <div class="card-body p-3">
        <div class="row no-gutters">
          <div class="col-md-12 col-lg-12 col-xl-12 p-1">

            <%= form_for([@project]) do |f| %>
            <div class="input-group">
                <%= f.file_field :uploads, multiple: true, required: true,  class: "form-control" %>
              <div class="input-group-append">
                <%= f.submit "Upload Files", class: "btn btn-primary" %>
              </div>
            </div>



            <% end %>

            <ul class="list-group list-group-flush">

            <% @project.uploads.each do |upload| %>
              <li class="list-group-item">
                <div class="media align-items-center">
                  <div class="media-body px-2">
                    <%= link_to upload.filename, rails_blob_path(upload, disposition: :attachment) %>
                  </div>

                  <% if current_user.try(:admin?) %>

                    <%= link_to url_for(controller: :projects, action: :delete_upload, id: @project.id, upload_id: upload.id), method: :delete,   data: { confirm: 'Are you sure?' } do %>
                      <span class="d-block text-light text-large font-weight-light">&times;</span>
                    <% end %>
                  <% end %>

                </div>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <!-- / Attached files -->

    <!-- Tabs -->
    <div class="nav-tabs-top mb-4">
      <ul class="nav nav-tabs">

        <li class="nav-item">
          <a class="nav-link active" data-toggle="tab" href="#project-discussion">Project Discussion</a>
        </li>

      </ul>
      <div class="tab-content">

        <!-- Discussion -->
        <div class="tab-pane fade show active" id="project-discussion">
          <%= render 'comments/form' %>

          <div id="commentdiv">
          <%= render @comments %>
          </div>


        </div>
        <!-- / Discussion -->


      </div>
    </div>
    <!-- / Tabs -->

  </div>
  <div class="col-md-4 col-xl-3">

    <!-- Project details -->
    <div class="card mb-4">
      <h6 class="card-header">Project details</h6>
      <ul class="list-group list-group-flush">
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div class="text-muted">Customer Name</div>
          <div><%= @project.customername %></div>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div class="text-muted">Customer email</div>
          <div><%= link_to @project.customeremail, "mailto:#{@project.customeremail}" %></div>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div class="text-muted">Customer phone</div>
          <div><%= link_to @project.customerphone, "tel:#{@project.customerphone}" %></div>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div class="text-muted">Created by</div>
          <div><%= @project.user.username %></div>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div class="text-muted">Created at</div>
          <div><%= @project.created_at.strftime("%m/%d/%Y") %></div>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div class="text-muted">Last update</div>
          <div><%= @project.updated_at.strftime("%m/%d/%Y") %></div>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div class="text-muted">Installer</div>
          <div><%= @project.installer %></div>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div class="text-muted">Project Manager</div>
          <div><%= @project.projmanager %></div>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div class="text-muted">Building</div>
          <div><%= @project.building %></div>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div class="text-muted">Location</div>
          <div><%= @project.rooms %></div>
        </li>

      </ul>
    </div>


  </div>
</div>