config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  namespace :admin do
    resources :installers

  end
  resources :comments
  devise_for :users
  resources :projects do
    get '/comments/:id', to: 'comments#destroy'
    resources :comments
  member do
    delete "delete_upload/:upload_id", action: :delete_upload
  end
end

  root 'home#index'


end

app/models/admin/installer.rb
class Admin::Installer < ApplicationRecord
end

app/controllers/admin/installers_controller.rb
class Admin::InstallersController < Admin::BaseController
  before_action :set_admin_installer, only: [:show, :edit, :update, :destroy]

  # GET /admin/installers
  # GET /admin/installers.json
  def index
    @admin_installers = Admin::Installer.all
  end

  # GET /admin/installers/1
  # GET /admin/installers/1.json
  def show
  end

  # GET /admin/installers/new
  def new
    @admin_installer = Admin::Installer.new
  end

  # GET /admin/installers/1/edit
  def edit
  end

  # POST /admin/installers
  # POST /admin/installers.json
  def create
    @admin_installer = Admin::Installer.new(admin_installer_params)

    respond_to do |format|
      if @admin_installer.save
        format.html { redirect_to @admin_installer, notice: 'Installer was successfully created.' }
        format.json { render :show, status: :created, location: @admin_installer }
      else
        format.html { render :new }
        format.json { render json: @admin_installer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/installers/1
  # PATCH/PUT /admin/installers/1.json
  def update
    respond_to do |format|
      if @admin_installer.update(admin_installer_params)
        format.html { redirect_to @admin_installer, notice: 'Installer was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_installer }
      else
        format.html { render :edit }
        format.json { render json: @admin_installer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/installers/1
  # DELETE /admin/installers/1.json
  def destroy
    @admin_installer.destroy
    respond_to do |format|
      format.html { redirect_to admin_installers_url, notice: 'Installer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_installer
      @admin_installer = Admin::Installer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_installer_params
      params.require(:admin_installer).permit(:installertype, :description)
    end
end

app/helpers/admin/installers_helper.rb
module Admin::InstallersHelper
end

app/helpers/installers_helper.rb
module InstallersHelper
end

app/views/admin/installers/_form.html.erb
<div class="card mb-4">
  <h6 class="card-header">
    Add New Installer
  </h6>
  <div class="card-body">
    <%= form_with(model: admin_installer, local: true) do |f| %>
    <% if admin_installer.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(admin_installer.errors.count, "error") %> prohibited this installer from being saved:</h2>

        <ul>
        <% admin_installer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <div class="form-group row">
    <%= f.label :installertype, 'Installer Type', { :class=>"col-form-label col-sm-2 text-sm-right" } %>

    <div class="col-sm-10">
      <%= f.text_field :installertype, { :class=>"form-control", autofocus: true, required: true } %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :description, 'Installer Type', { :class=>"col-form-label col-sm-2 text-sm-right" } %>

    <div class="col-sm-10">
      <%= f.text_field :description, { :class=>"form-control", autofocus: true, required: true } %>
    </div>
  </div>
</div>

<div class="form-group row">
  <div class="col-form-label col-sm-2 text-sm-right">
  </div>


  <div class="col-sm-10">

    <%= button_tag type: 'submit', class: "btn btn-primary" do %>
      <span class="ion ion-md-add"></span> &nbsp;&nbsp;<% if ( f.object.new_record? ) %>Add Installer<% else %>Update Installer<% end %>

    <% end %>
    <%= link_to 'Cancel', admin_installers_path, { :class=>"btn btn-secondary" } %>
  </div>

</div>

<% end %>
</div>

app/views/admin/installers/edit.html.erb
<h1>Editing Admin Installer</h1>

<%= render 'form', admin_installer: @admin_installer %>

app/views/admin/installers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Installers</h1>

<table>
  <thead>
    <tr>
      <th>Installertype</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_installers.each do |admin_installer| %>
      <tr>
        <td><%= admin_installer.installertype %></td>
        <td><%= admin_installer.description %></td>
        <td><%= link_to 'Show', admin_installer %></td>
        <td><%= link_to 'Edit', edit_admin_installer_path(admin_installer) %></td>
        <td><%= link_to 'Destroy', admin_installer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Installer', new_admin_installer_path %>

app/views/admin/installers/new.html.erb
<h1>New Admin Installer</h1>

<%= render 'form', admin_installer: @admin_installer %>

app/views/admin/installers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Installertype:</strong>
  <%= @admin_installer.installertype %>
</p>

<p>
  <strong>Description:</strong>
  <%= @admin_installer.description %>
</p>

<%= link_to 'Edit', edit_admin_installer_path(@admin_installer) %> |
<%= link_to 'Back', admin_installers_path %>