config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  namespace :admin do
    resources :installers

  end
  resources :comments
  devise_for :users
  resources :projects do
    get '/comments/:id', to: 'comments#destroy'
    resources :comments
  member do
    delete "delete_upload/:upload_id", action: :delete_upload
  end
end

  root 'home#index'


end

app/views/layouts/partials/_layout-footer.html.erb
<!-- Layout footer -->
<nav class="layout-footer footer bg-footer-theme">
  <div class="container-fluid container-p-x pb-3">
    <a href="#" class="footer-link pt-3">Link 1</a>
    <a href="#" class="footer-link pt-3 ml-4">Link 2</a>
  </div>
</nav>
<!-- / Layout footer -->

app/views/layouts/partials/_layout-navbar.html.erb
<!-- Layout navbar -->
<nav class="layout-navbar navbar navbar-expand-lg align-items-lg-center bg-white container-p-x" id="layout-navbar">

  <!-- Brand demo (see app/assets/stylesheets/demo.css) -->
  <a href="/" class="navbar-brand app-brand demo d-lg-none py-0 mr-4">
    <span class="app-brand-logo demo bg-primary">
      <svg viewBox="0 0 148 80" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><linearGradient id="a" x1="46.49" x2="62.46" y1="53.39" y2="48.2" gradientUnits="userSpaceOnUse"><stop stop-opacity=".25" offset="0"></stop><stop stop-opacity=".1" offset=".3"></stop><stop stop-opacity="0" offset=".9"></stop></linearGradient><linearGradient id="e" x1="76.9" x2="92.64" y1="26.38" y2="31.49" xlink:href="#a"></linearGradient><linearGradient id="d" x1="107.12" x2="122.74" y1="53.41" y2="48.33" xlink:href="#a"></linearGradient></defs><path style="fill: #fff;" transform="translate(-.1)" d="M121.36,0,104.42,45.08,88.71,3.28A5.09,5.09,0,0,0,83.93,0H64.27A5.09,5.09,0,0,0,59.5,3.28L43.79,45.08,26.85,0H.1L29.43,76.74A5.09,5.09,0,0,0,34.19,80H53.39a5.09,5.09,0,0,0,4.77-3.26L74.1,35l16,41.74A5.09,5.09,0,0,0,94.82,80h18.95a5.09,5.09,0,0,0,4.76-3.24L148.1,0Z"></path><path transform="translate(-.1)" d="M52.19,22.73l-8.4,22.35L56.51,78.94a5,5,0,0,0,1.64-2.19l7.34-19.2Z" fill="url(#a)"></path><path transform="translate(-.1)" d="M95.73,22l-7-18.69a5,5,0,0,0-1.64-2.21L74.1,35l8.33,21.79Z" fill="url(#e)"></path><path transform="translate(-.1)" d="M112.73,23l-8.31,22.12,12.66,33.7a5,5,0,0,0,1.45-2l7.3-18.93Z" fill="url(#d)"></path></svg>
    </span>
    <span class="app-brand-text demo font-weight-normal ml-2">Vastt PM</span>
  </a>

  <% if local_assigns[:hide_toggle] != true %>
  <!-- Sidenav toggle (see app/assets/stylesheets/demo.css) -->
  <div class="layout-sidenav-toggle navbar-nav d-lg-none align-items-lg-center mr-auto">
    <a class="nav-item nav-link px-0 mr-lg-4" href="javascript:void(0)">
      <i class="ion ion-md-menu text-large align-middle"></i>
    </a>
  </div>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#layout-navbar-collapse">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="navbar-collapse collapse" id="layout-navbar-collapse">
    <!-- Divider -->
    <hr class="d-lg-none w-100 my-2">

    <div class="navbar-nav align-items-lg-center">
      <!-- Search -->
      <label class="nav-item navbar-text navbar-search-box p-0 active">
        <i class="ion ion-ios-search navbar-icon align-middle"></i>
        <span class="navbar-search-input pl-2">
          <input type="text" class="form-control navbar-text mx-2" placeholder="Search..." style="width:200px">
        </span>
      </label>
    </div>

    <div class="navbar-nav align-items-lg-center ml-auto">




      <!-- Divider -->
      <div class="nav-item d-none d-lg-block text-big font-weight-light line-height-1 opacity-25 mr-3 ml-1">|</div>

      <div class="demo-navbar-user nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
          <span class="d-inline-flex flex-lg-row-reverse align-items-center align-middle">
            <!-- <img src="/img/avatars/1.png" alt class="d-block ui-w-30 rounded-circle"> -->
            <span class="px-1 mr-lg-2 ml-2 ml-lg-0"><% if user_signed_in? %><%= current_user.username %><% end %></span>
          </span>
        </a>
        <div class="dropdown-menu dropdown-menu-right">
          <%= link_to(destroy_user_session_path, :method => :delete, :class => "dropdown-item")  do %>
          <i class="ion ion-ios-log-out text-danger"></i> &nbsp; Log Out
          <% end %>

        </div>
      </div>
    </div>
  </div>
</nav>
<!-- / Layout navbar -->

app/views/layouts/partials/_layout-sidenav.html.erb
<div id="layout-sidenav" class="<% if local_assigns[:horizontal] == true %>layout-sidenav-horizontal sidenav-horizontal container-p-x flex-grow-0<% else %>layout-sidenav sidenav-vertical<% end %> sidenav bg-sidenav-theme"
   data-turbolinks='false'>
  <% if local_assigns[:horizontal] != true %>
  <!-- Brand demo (see assets/css/demo/demo.css) -->
  <div class="app-brand demo">
    <!-- <span class="app-brand-logo demo bg-primary">

    </span> -->
    <a href="/" class="app-brand-text demo sidenav-text font-weight-normal ml-2">VASTT</a>
    <a href="javascript:void(0)" class="layout-sidenav-toggle sidenav-link text-large ml-auto">
      <i class="ion ion-md-menu align-middle"></i>
    </a>
  </div>

  <div class="sidenav-divider mt-0"></div>
  <% end %>
  <!-- Inner -->
  <ul class="sidenav-inner<% if local_assigns[:horizontal] != true %> py-1<% end %>">

    <!-- Projects -->

    <li class="sidenav-item<%= current_page?('/projects') || request.fullpath.start_with?('/projects/') || current_page?(root_path) ? ' active' : '' %>">
      <%= link_to projects_path, class: "sidenav-link" do %><i class="sidenav-icon ion ion-ios-albums"></i><div>Projects</div><% end %>
    </li>
    <% if current_user.try(:admin?) %>
    <li class="sidenav-item<%= request.fullpath.start_with?('/admin/') || request.path == '/' ? ' active open' : '' %>">
      <a href="javascript:void(0)" class="sidenav-link sidenav-toggle"><i class="sidenav-icon ion ion-md-speedometer" ></i><div>Admin</div></a>
      <ul class="sidenav-menu">
    <li class="sidenav-item<%= current_page?('/admin/installers') || request.fullpath.start_with?('/admin/installers/')  ? ' active' : '' %>">
      <%= link_to admin_installers_path, class: "sidenav-link" do %><i class="sidenav-icon ion ion-ios-albums"></i><div>Installers</div><% end %>
    </li>
      </ul>
    </li>
    <% end %>




  </ul>
</div>
<!-- / Layout sidenav -->